[package]
name = "snowpatch"
version = "0.1.0"
authors = ["Russell Currey <ruscur@russell.cc>", "Andrew Donnellan <andrew.donnellan@au1.ibm.com>"]
description = "continuous integration for patch-based workflows"
readme = "README.md"
license = "GPL-2.0+"

[[bin]]
name = "snowpatch"

[dependencies]
hyper = "0.7.2"
git2 = "0.3"
rustc-serialize = "0.3.18"
url = "*"
mime = "*"
