[package]
name = "snowpatch"
version = "0.1.0"
authors = ["Russell Currey <ruscur@russell.cc>", "Andrew Donnellan <andrew.donnellan@au1.ibm.com>"]

[dependencies]
hyper = "0.7.2"
git2 = "0.3"
rustc-serialize = "0.3.18"
url = "*"
mime = "*"
