#
# snowpatch - continuous integration for patch-based workflows
#
# Copyright (C) 2016 IBM Corporation
# Authors:
#     Russell Currey <ruscur@russell.cc>
#     Andrew Donnellan <andrew.donnellan@au1.ibm.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Cargo.toml - cargo build configuration file
#

[package]
name = "snowpatch"
version = "0.1.0"
authors = ["Russell Currey <ruscur@russell.cc>", "Andrew Donnellan <andrew.donnellan@au1.ibm.com>"]
description = "continuous integration for patch-based workflows"
readme = "README.md"
license = "GPL-2.0+"

[[bin]]
name = "snowpatch"

[dependencies]
hyper = "0.9"
git2 = "0.3"
rustc-serialize = "0.3"
url = "0.5"
mime = "0.2"
toml = "0.1"
tempdir = "0.3"
docopt = "0.6"

[dev-dependencies]
yup-hyper-mock = "1.3"
log = "0.3"
