[patchwork]
url = "https://russell.cc/patchwork"
port = 443 #optional
user = "ruscur" #TODO: make pushing results configurable,
pass = "banana" #      and these arguments optional

[jenkins]
url = "https://jenkins.ozlabs.ibm.com"
port = 443
# TODO: jenkins auth (our testing jenkins has no auth)

[projects]

    # the name of the project must be as is in patchwork
    [projects.skiboot]
    repository = "/home/ruscur/Documents/skiboot"
    branch = "master" # the branch to base from
    remote_name = "github"
    remote_uri = git@github.com:ruscur/skiboot.git
    jobs = []
    push_results = true

    [projects.linuxppc-dev]
    repository = "/home/ruscur/Documents/linux"
    branch = "master" # TODO: multiple merge branches
    remote_name = "github"
    remote_uri = git@github.com:ruscur/linux.git
    push_results = true
    jobs = ["linux-build-manual"]

