[patchwork]
url = "https://russell.cc/patchwork"
port = 443 #optional
user = "ruscur" #TODO: make pushing results configurable,
pass = "banana" #      and these arguments optional
polling_interval = 10 # polling interval in minutes

[jenkins]
url = "https://jenkins.ozlabs.ibm.com"
port = 443
# TODO: jenkins auth (our testing jenkins has no auth)

[projects]

    # the name of the project must be as is in patchwork
    [projects.skiboot]
    repository = "/home/ruscur/Documents/skiboot"
    branch = "master" # the branch to base from
    remote_name = "github"
    remote_uri = "git@github.com:ruscur/skiboot.git"
    jobs = {}
    push_results = true

    [projects.linuxppc-dev]
    repository = "/home/ruscur/Documents/linux"
    branch = "master" # TODO: multiple merge branches
    remote_name = "github"
    remote_uri = "git@github.com:ruscur/linux.git"
    push_results = true

        [[projects.linuxppc-dev.jobs]]
        job = "linux-build-manual"
        remote = "GIT_REPO_TO_USE"
        branch = "GIT_REF_TO_BUILD"
        USER_EMAIL = "username"
        DEFCONFIG_TO_USE = "pseries_le_defconfig"

        [[projects.linuxppc-dev.jobs]]
        job = "linux-build-manual"
        remote = "GIT_REPO_TO_USE"
        branch = "GIT_REF_TO_BUILD"
        USER_EMAIL = "username"
        DEFCONFIG_TO_USE = "ppc64le_defconfig"